services:
  mongo:
    image: mongo:6
    container_name: auth-mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: authService
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  auth-service:
    build: ./services/auth
    container_name: auth-service
    restart: always
    env_file:
      - ./services/auth/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    command: npm run dev

volumes:
  mongo-data:
